### ISSUE TITLE
Getting error on empty Classes

### ISSUE THREAD

**Issue by guilhermef** [heynemann/pyvows#126]
If I try to organize my test using empty classes, like this:

```python
class NormalizeURL(TornadoHTTPContext):

    class WhenStartsWithHttp(TornadoHTTPContext):
        def topic(self):
            return loader._normalize_url('http://some.url')

        def should_return_same_url(self, topic):
            expect(topic).to_equal('http://some.url')
```
I get an error

```
Error in topic:
Function %s does not have a code property

Traceback (most recent call last):
        File "/Users/guilhermef/.virtualenvs/thumbor/lib/python2.7/site-packages/pyvows/runner/gevent.py", line 97, in _run_setup_and_topic
    topic_list = get_topics_for(topic_func, ctx_obj)
        File "/Users/guilhermef/.virtualenvs/thumbor/lib/python2.7/site-packages/pyvows/runner/utils.py", line 45, in get_topics_for
    raise RuntimeError('Function %s does not have a code property')
RuntimeError: Function %s does not have a code property

      Nested tests following this error have not been run.
```

I think It should be allowed to have empty classes, to keep tests organized.

**Comment by heynemann** [comment]
I think that if we do not find the "topic" method, we should use None as topic.
